# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-04 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TapelessIngest', '0002_auto_20190604_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestClipJob',
            fields=[
                ('clip', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tasks', serialize=False, to='TapelessIngest.Clip')),
                ('status', models.CharField(max_length=48)),
                ('progress', models.IntegerField(default=None, null=True, verbose_name='Ingest progress')),
                ('error', models.CharField(default=None, max_length=255, null=True, verbose_name='Error message')),
                ('exception', models.CharField(default=None, max_length=65535, null=True, verbose_name='Exception message')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TapelessIngest.AggregateIngestJob')),
            ],
        ),
    ]
