# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-04 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TapelessIngest', '0003_ingestclipjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestTaskJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default=None, max_length=255, null=True, verbose_name='Task name')),
                ('status', models.CharField(max_length=48)),
                ('progress', models.IntegerField(default=None, null=True, verbose_name='Ingest progress')),
                ('error', models.CharField(default=None, max_length=255, null=True, verbose_name='Error message')),
                ('exception', models.CharField(default=None, max_length=65535, null=True, verbose_name='Exception message')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingestclipjob',
            name='job',
        ),
        migrations.AlterField(
            model_name='ingestclipjob',
            name='clip',
            field=models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='jobs', serialize=False, to='TapelessIngest.Clip'),
        ),
        migrations.AddField(
            model_name='ingesttaskjob',
            name='job',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TapelessIngest.IngestClipJob'),
        ),
    ]
