# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-04 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapelessIngest', '0004_auto_20190604_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingestjob',
            name='clip',
        ),
        migrations.RemoveField(
            model_name='ingestjob',
            name='job',
        ),
        migrations.DeleteModel(
            name='IngestJob',
        ),
    ]
