# Generated by Django 2.2.11 on 2020-11-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapelessIngest', '0008_auto_20200922_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='collections_ignore_folder',
            field=models.TextField(blank=True, default=''),
        ),
    ]
