# Generated by Django 2.2.11 on 2020-11-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapelessIngest', '0009_settings_collections_ignore_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='collections_rename_folder',
            field=models.TextField(blank=True, default=''),
        ),
    ]
