# Generated by Django 2.2.17 on 2021-09-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapelessIngest', '0010_settings_collections_rename_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='collections_ignore_folder',
            new_name='collections_ignore_folder_str',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='collections_rename_folder',
            new_name='collections_rename_folder_str',
        ),
        migrations.AlterField(
            model_name='settings',
            name='collections_ignore_folder_str',
            field=models.TextField(blank=True, db_column='collections_ignore_folder', default=''),
        ),
        migrations.AlterField(
            model_name='settings',
            name='collections_rename_folder_str',
            field=models.TextField(blank=True, db_column='collections_rename_folder', default=''),
        ),
    ]
