# Generated by Django 2.2.17 on 2021-09-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapelessIngest', '0012_auto_20210929_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='clips_total',
            field=models.IntegerField(default=0),
        ),
    ]
