# Generated by Django 2.2.17 on 2021-09-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapelessIngest', '0013_folder_clips_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='folders',
            field=models.ManyToManyField(null=True, to='TapelessIngest.Folder'),
        ),
    ]
