# Generated by Django 2.2.17 on 2021-09-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapelessIngest', '0014_clip_folders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='folder',
        ),
    ]
