# Generated by Django 2.2.17 on 2021-10-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TapelessIngest', '0015_remove_clip_folder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('path', 'storage_id')},
        ),
    ]
